Order request component
GSG-G9/service-seeker pull request #104
Opened 2021-04-05 09:43 UTC by mAbadsa

### Create order request component
**This component enables the customer to send a request to the providers.**

- Provider Information.
- Rating star.
- Details input and submit button.

_This Component will be used in a popup modal on the Landing page._

2021-04-06 10:01 UTC, zeinjendeya requested changes

2021-04-06 10:01 UTC, zeinjendeya commented on client/src/App/index.js
> +          <Orders />
why did you leave this here?

2021-04-06 10:01 UTC, zeinjendeya commented on client/src/Pages/Orders/index.js
> +            </Button>
in this case, I suppose that we put the button inside the Form element since it performs a mission in it.

2021-04-08 18:22 UTC, mariamisa approved these changes

2021-04-08 18:22 UTC, merged