delete order route
GSG-G9/service-seeker pull request #106
Opened 2021-04-05 12:31 UTC by zeinjendeya

- created query that checks the user id, relation id (order req), and state to delete the order.
- created a controller that takes the id from req params and takes the user id from the request itself the deletes the order.

2021-04-06 07:02 UTC, mAbadsa commented on server/controller/user/deleteOrder.js
> +      .json({ status: 200, message: 'order deleted successfully' });
Replace status with statusCode.

2021-04-06 13:15 UTC, mariamisa requested changes
change files name to orderRequest

2021-04-06 14:36 UTC, mAbadsa approved these changes, later dismissed

2021-04-07 10:36 UTC, mariamisa approved these changes

2021-04-07 10:36 UTC, merged

2021-04-07 12:02 UTC, mAbadsa commented on server/controller/user/deleteOrderRequest.js
> +      .status(201)
status = 200 not 201