post order provider
GSG-G9/service-seeker pull request #107
Opened 2021-04-06 09:50 UTC by zeinjendeya

- created a 3 query:
    - get Order By ID: to check the status
    - change State Order Request: to change the state in the order-request table from pending to accepted
    - accept orders: to insert the new order into the orders table with the arrival time and state
- created a controller: to use all three queries and check state then insert then send a request with 201 status code and a message that the request was accepted successfully. 

#53

2021-04-06 13:14 UTC, mariamisa requested changes

2021-04-06 13:14 UTC, mariamisa commented on server/controller/provider/orderAccept.js
> +    }
you can directly update the request without getting the data

2021-04-06 13:14 UTC, mariamisa commented on server/database/queries/provider/changeStateOrderRequest.js
> +    text: "UPDATE ordes_request SET state='accepted' WHERE id=$1'",
you need to check if the owner of this order is the logged provider

2021-04-06 13:14 UTC, mariamisa commented on server/database/queries/provider/getOrderProvider.js
> +module.exports = getOrderByUserID;
no need to get orderRequest

2021-04-06 13:14 UTC, mariamisa commented on server/router/user.js
> +router.post('/provider/orders', orderAcceptValidation, acceptOrderController);
this route relates to the provider file and needs to providerProtectedMIddelware the user shouldn't can access these endpoints

2021-04-07 16:47 UTC, mAbadsa approved these changes, later dismissed

2021-04-08 15:30 UTC, mariamisa approved these changes

2021-04-08 15:30 UTC, merged