send the bill through email
GSG-G9/service-seeker pull request #167
Opened 2021-04-19 05:41 UTC by mAbadsa

Relates #157

2021-04-19 22:42 UTC, Ahmed-aed submitted a review, later dismissed

2021-04-20 04:21 UTC, mariamisa requested changes
change the msg on the finish state to :
```js
res.json({
      statusCode: 200,
      message:
        state === 'Finished'
          ? 'your order completed successfully,check you email you will receive an email contains your order bill'
          : ` orders ${state}`,
    });
```

2021-04-20 04:21 UTC, mariamisa commented on server/controller/orders/updateOrderState.js
> +        providerPriceHour = providerData.price_hour;
* you cant declare variables inside the switch so you need to declare ``` let providerData ``` outside the switch then give it the provider data.
```js
   [providerData] = (await getProviderDataById(providerId)).rows;

```
*  remove the comment code
* delete unused query file(getPriceHourProvider)  inside the require .

2021-04-20 04:21 UTC, mariamisa commented on server/controller/orders/updateOrderState.js
> +          },
I think the content of the email should be dynamic data according to the order and users information

2021-04-20 04:21 UTC, mariamisa commented on server/utils/sendBill.js
> +  { total, hourPrice, hourNumber, description, client, provider },
more clear to pass the object of email content and destructure the value , like this :
```js
const sendTheBill = async (to, subject, content, next) => {
  try {
    const {
      total,
      hourPrice,
      hourNumber,
      description,
      client,
      provider,
    } = content;
```

2021-04-20 04:21 UTC, mariamisa commented on server/utils/sendBill.js
> +        pass: process.env.SENDER_EMAIL_PASSWORD,
I like that you hide your email information, for more improvement destruct the values from process.env
```js
    const { NODEMAILER_SENDER_EMAIL, SENDER_EMAIL_PASSWORD } = process.env;

```

2021-04-20 04:21 UTC, mariamisa commented on server/utils/sendBill.js
> +          font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;"><span style="font-weight:bold">Provider</span></th>
refactor the html content, remove all the duplicate style
* if you need to use colors inside the email, please use our site colors

2021-04-20 04:21 UTC, mariamisa commented on server/controller/orders/updateOrderState.js
>      if (!order) {
refactor the condition to 
```js
if (!order) {
      throw boomify(404, 'There is no order');
    } else if (order.state === state || order.state === 'Finished') {
      throw boomify(400, `the order is already ${order.state}`);
    } else if (order.state === 'Accepted' && state !== 'Start') {
      throw boomify(409, 'the order is not started yet');
    }
```

2021-04-20 04:50 UTC, mariamisa requested changes

2021-04-20 04:50 UTC, mariamisa commented on server/controller/orders/updateOrderState.js
> +          `${userData}, ${providerData.email}`,
test your email and check if you pass the right data for first email 
```js
          `${userData.email}, ${providerData.email}`,

```

2021-04-20 04:50 UTC, mariamisa commented on server/controller/orders/updateOrderState.js
> +    });
* hete you store the all result from query , destruct the rows to access user data 
```js
const { rows: result } = await getUserData({
      userId: order.user_id,
    });
    const [userData] = result;
```

2021-04-20 13:30 UTC, merged