React Setup
GSG-G9/service-seeker pull request #60
Opened 2021-03-25 16:27 UTC by Osama-you

2021-03-26 13:36 UTC, zeinjendeya submitted a review, later dismissed

2021-03-26 15:52 UTC, mAbadsa requested changes

2021-03-26 15:52 UTC, mAbadsa commented on client/src/Utils/routes.constant.js
> +export const PROVIDER_PROFILE_PAGE = '/';
Profile page on route = /profile/:id

2021-03-26 21:35 UTC, mariamisa approved these changes

2021-03-27 08:57 UTC, mAbadsa approved these changes

2021-03-27 10:03 UTC, merged