33 signup backend
GSG-G9/service-seeker pull request #87
Opened 2021-03-29 16:05 UTC by mAbadsa

**Signup backend side.**

- Create a signup controller to handle adding a new user.
- Create the signup input validation.
- Create add new user database query.

2021-03-30 07:39 UTC, zeinjendeya submitted a review, later dismissed

2021-03-30 09:41 UTC, Ahmed-aed approved these changes

2021-03-30 09:53 UTC, Ahmed-aed submitted a review, later dismissed

2021-03-30 15:21 UTC, mariamisa requested changes

2021-03-30 15:21 UTC, mariamisa commented on server/database/queries/provider/createNewProvider.js
> +    text: 'INSERT INTO providers (user_id) VALUES ($1) RETURNING id;',
no need to returning the id

2021-03-30 15:21 UTC, mariamisa commented on server/controller/user/userSignup.js
> +    // eslint-disable-next-line object-curly-newline
don't disable eslint role

2021-03-30 15:21 UTC, mariamisa commented on server/controller/user/userSignup.js
> +const { createNewProvider } = require('../../database/queries/provider');
create index.js for all queries

2021-03-30 17:32 UTC, mariamisa submitted a review, later dismissed

2021-03-31 06:43 UTC, Osama-you submitted a review, later dismissed

2021-03-31 12:34 UTC, merged